name: Build and test
on: [push, pull_request]
jobs:  
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ "22.6" ]
    name: Node ${{ matrix.node-version }}
    steps:
      - name: Checkout DS repo
        uses: actions/checkout@v4
        with:
          repository: mff-uk/dataspecer
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create .env for conceptual-model-editor
        run: cp applications/conceptual-model-editor/.env.example applications/conceptual-model-editor/.env
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      
      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-repo-data     
          path: .

      #- name: Test
        #run: npm run test

  print_build_content:
    name: Print build content
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build repo
        uses: actions/download-artifact@v4
        with:
          name: build-repo-data
      - name: Print content
        run: ls -la      

  run_CME:
    name: Run CME
    needs: build
    runs-on: ubuntu-latest    
    steps:            
      # Not enough - we have to install and build explictly here anyways, I don't know what is missing
      - name: Download build repo
        uses: actions/download-artifact@v4
        with:
          name: build-repo-data          
      - name: Install Everything again
        run: npm ci
      - name: Build everything again
        run: npm run build
      - name: CME directory content
        working-directory: applications/conceptual-model-editor        
        run: ls -la 
      - name: Build conceptual model editor
        working-directory: applications/conceptual-model-editor        
        run: npm run build      
      - name: Run conceptual model editor
        working-directory: applications/conceptual-model-editor        
        run: npm run dev &
      - run: npm install wait-on@8.0.2  
      - run: npx wait-on http://localhost:5173/diagram  # Wait until it's up
      - run: curl http://localhost:5173/diagram  # Perform actions (e.g., testing)            
      - shell: bash
        run: |
          mkdir dataspecer-repo
          cd dataspecer-repo
      - run: ls -la
        working-directory: ./dataspecer-repo
      - uses: actions/checkout@v4
        with:
          path: ./dataspecer-repo
      - run: npm install
        working-directory: ./dataspecer-repo
      - run: node src/index.js
        working-directory: ./dataspecer-repo
      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pop     
          path: ./dataspecer-repo/downloads
      - name: Download build repo
        uses: actions/download-artifact@v4
        with:
          name: pop          
      - run: ls -la
        working-directory: ./dataspecer-repo
      - run: kill $(jobs -p)
        
#  run_DS_backend:
#    name: Run DS backend
#    needs: build
#    runs-on: ubuntu-latest    
#    steps:      
#      - name: Download build repo
#        uses: actions/download-artifact@v4
#        with:
#          name: build-repo-data
#      - name: Update database
#        working-directory: services/backend
#        run: npm run update-database
#      - name: Run the backend
#        working-directory: services/backend
#        run: npm run start


