name: Build and test
on: [push, pull_request]
jobs:  
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ "22.6" ]
    name: Node ${{ matrix.node-version }}
    steps:
      - name: Checkout DS repo
        uses: actions/checkout@v4
        with:
          repository: mff-uk/dataspecer
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create .env for conceptual-model-editor
        run: cp applications/conceptual-model-editor/.env.example applications/conceptual-model-editor/.env
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      #- name: Test
        #run: npm run test

  run:
    name: Run DS backend
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print content
        run: ls -la            
