# https://lannonbr.com/blog/2019-12-09-git-commit-in-actions/

name: Commit date to master
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > time.txt        
