# https://lannonbr.com/blog/2019-12-09-git-commit-in-actions/

name: Commit date to master
on: 
  push:
    paths-ignore:
      - 'time.txt'
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false 

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > time.txt     
          
      - name: setup git config
        env:
          MY_MAIL: ${{ secrets.MY_MAIL }}
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # When I want to commit as myself
          # git config --global user.name "RadStr"
          # git config --global user.email ${MY_MAIL}
          
        
      - name: commit
        env:
          PAT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_GITHUB }}
        run: |
          # Stage the file, commit and push
          git add time.txt
          git commit -m "New date commit"
          git remote set-url origin https://${PAT_TOKEN}@github.com/RadStr/test-repo-for-gh-actions.git
          git push origin main
#          git push            
# Pushing is based on https://sameeradissanayaka.medium.com/how-to-use-github-actions-to-push-code-commit-to-another-branch-af04d8406f08  
