# Taken from https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow#passing-data-between-jobs-in-a-workflow

name: Share data between jobs

on: 
  push:
    paths-ignore:
      - 'time.txt'

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir output
          expr 3 + 7 > output/math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: output/math-homework.txt
          retention-days: 1

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: homework_pre
          #path: output/    # We have to specify the directory, if it is not the root one
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > output/math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v4
        with:
          name: homework_final
          path: output/math-homework.txt
          retention-days: 1

  job_3:
    name: Display results
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: homework_final
          #path: output/    # We have to specify the directory, if it is not the root one
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value


  perform_commit:
    runs-on: ubuntu-latest
    needs: job_2    
    steps:
      - name: Download the file to commit
        uses: actions/download-artifact@v4
        with:
          name: homework_final    # Using the name defined in GH action, not the path name
          #path: output/    # We have to specify the directory, if it is not the root one
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Trying to commit the result to this repo"
          add: '["homework_final"]'
      - name: Print result to console
        run: Success!
